
name: CI

on:
  push:
    branches: 
      - '*'
      
  pull_request:
    branches:
      - '*'
  
  workflow_dispatch:
    
jobs:
  build_windows:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    
    - name: Hash
      shell: cmd
      working-directory: ./
      run: echo '%GITHUB_SHA:~0,7%' > test.txt
